### PR TITLE
Fix recurrence goal bug that doesn't schedule goal if recurrence interval is greater than plan

### LINKED ISSUE #703: Fix bug that doesn't schedule goal if recurrence interval is greater than plan window
If an activity recurrence goal's specified interval is greater than the time in the plan window the goal will not schedule any instances.

However, if the goal interval is less than the plan's duration with an activity duration that goes over, an instance will still be scheduled (activity_length + recurrence_interval > plan_length). The activity is also scheduled if the recurrence interval is less than the plan's duration.

### PR DESCRIPTION
**Pull request by jmdelfa**
* **Tickets addressed:** Closes https://github.com/NASA-AMMOS/aerie/issues/703
* **Review:** By commit
* **Merge strategy:** Merge (no squash)

## Description
Add modifications to Goal and RecurrenceGoal to make consistency checks between goal duration (if fixed), goal time windows and Planning Horizon

## Verification
Execution of all scheduler and e2e tests

## Documentation
Extension of RecurrenceGoal documentation is being produced

## Future work
N/A

### CODE REVIEW

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/Goal.java [hunk 1]
```diff
@@ -223,6 +233,13 @@ protected Goal fill(Goal goal) {
         goal.temporalContext = new WindowsWrapperExpression(windows);
       }
 
+      if (planHorizon == null) {
```
Comment (skovati) [inline scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/Goal.java:236]: Maybe 
```suggestion
      Objects.requireNonNull(planHorizon);
```
is more appropriate?

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java [hunk 2]
```diff
@@ -15,6 +20,7 @@
 import org.jetbrains.annotations.NotNull;
 
 import java.util.List;
+import java.util.*;
```
Comment (skovati) [inline scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java]: Minor, but maybe change this to the specific imports being used?
```suggestion
```

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/Problem.java [hunk 3]
```diff
@@ -132,6 +132,16 @@ public void setGoals(List<Goal> goals){
...
+  /*
+  public void setGoalsTest(List<Goal> goals){
+    goalsOrderedByPriority.clear();
+    for(Goal goal : goals){
+      goal
+    }
+    goalsOrderedByPriority.addAll(goals);
+  }*/
+
+
```
Comment (skovati) [inline scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/Problem.java]: Possibly unused?
```suggestion
```

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java [hunk 4]
```diff
@@ -204,7 +209,7 @@ public void testRecurrenceBabyWindow() {
       logger.debug(a.startOffset().toString());
     }
 
-    assertFalse(TestUtility.activityStartingAtTime(plan,Duration.of(1, Duration.SECONDS), activityType));
+    assertTrue(TestUtility.activityStartingAtTime(plan,Duration.of(1, Duration.SECONDS), activityType));
```
Comment (skovati) [inline scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java:225]: Why is this test now expected to return the inverse?

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java [hunk 5]
```diff
@@ -293,9 +300,9 @@ public void testRecurrenceWindowsCutoffMidInterval() {
       logger.debug(a.startOffset().toString());
     }
 
-    assertFalse(TestUtility.activityStartingAtTime(plan,Duration.of(1, Duration.SECONDS), activityType)); //cutting off mid interval should fail, i.e. no scheduling
+    assertTrue(TestUtility.activityStartingAtTime(plan,Duration.of(1, Duration.SECONDS), activityType)); //cutting off mid interval should fail, i.e. no scheduling
```
Comment (skovati) [inline scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java]: Same question as above. If this is intentional, maybe we should change the associated comment.

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestUtility.java [hunk 6]
```diff
@@ -19,6 +19,9 @@
 
 public class TestUtility {
 
+  public static boolean emptyPlan(Plan plan) {
+    return plan.getActivities().size() == 0;
```
Comment (skovati) [inline scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestUtility.java]: Minor:
```suggestion
    return plan.getActivities().isEmpty();
```

**Review by skovati — COMMENTED** [review]
Looks good! Just a few minor comments I initially had.

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java [hunk 7]
```diff
@@ -3,8 +3,13 @@
 import gov.nasa.jpl.aerie.constraints.model.EvaluationEnvironment;
 import gov.nasa.jpl.aerie.constraints.model.SimulationResults;
 import gov.nasa.jpl.aerie.constraints.time.Interval;
+import gov.nasa.jpl.aerie.constraints.time.Segment;
 import gov.nasa.jpl.aerie.constraints.time.Windows;
+import gov.nasa.jpl.aerie.constraints.tree.DiscreteProfileFromDuration;
+import gov.nasa.jpl.aerie.constraints.tree.DurationLiteral;
 import gov.nasa.jpl.aerie.merlin.protocol.types.Duration;
+import gov.nasa.jpl.aerie.merlin.protocol.types.DurationType;
+import gov.nasa.jpl.aerie.scheduler.constraints.activities.ActivityCreationTemplate;
```
Comment (Mythicaeda) [inline scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java]: The only import that was added that is used is `DurationType`.

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java [hunk 8]
```diff
@@ -414,6 +414,9 @@ ActivityExpression build() {
    */
   protected @Nullable Expression<? extends Profile<?>> duration;
 
+  public @Nullable
+  Expression<? extends Profile<?>>  getDuration() { return duration; }
+
```
Comment (Mythicaeda) [inline scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java]: I could find no usages of this method. Could you tell me when it's used?

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java [hunk 9]
```diff
@@ -195,16 +210,14 @@ private java.util.Collection<MissingActivityConflict> makeRecurrenceConflicts(Du
...
-
     for (var intervalT = start.plus(recurrenceInterval.max);
          ;
          intervalT = intervalT.plus(recurrenceInterval.max)
     ) {
       final var windows = new Windows(false).set(Interval.betweenClosedOpen(intervalT.minus(recurrenceInterval.max), Duration.min(intervalT, end)), true);
-      conflicts.add(new MissingActivityTemplateConflict(this, windows, this.getActTemplate(), new EvaluationEnvironment()));
+      if(windows.iterateEqualTo(true).iterator().hasNext()){
+        conflicts.add(new MissingActivityTemplateConflict(this, windows, this.getActTemplate(), new EvaluationEnvironment()));
+      }
```
Comment (Mythicaeda) [inline scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java:215]: What does this if statement do? When is it `false`?

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java (hunk 2 above)
Comment (jmdelfa) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java]: Agree. It was actually unused as the specific imports were already added.

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/Problem.java (hunk 3 above)
Comment (jmdelfa) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/model/Problem.java]: Agree. Removed

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java (hunk 4 above)
Comment (jmdelfa) [reply scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java:225]: The test was wrong in the first place. Below a detailed explanation:
The plan horizon ranges from [0,20).
The recurrent activities can be placed inside the following window: [1,2)
The activities instantiating the goal have a duration of 1
The activities should repeat every 5 time units

It is therefore possible to place an activity in time 1, with a duration of 1
Graphically
    // RECURRENCE WINDOW: [+----+----+----+----]
    // GOAL WINDOW:              [+-------------------]
    // RESULT:                            [+-------------------]

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java (hunk 5 above)
Comment (jmdelfa) [reply scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java]: See answer above

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestUtility.java (hunk 6 above)
Comment (jmdelfa) [reply scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestUtility.java]: Agree. Corrected

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java (hunk 7 above)
Comment (jmdelfa) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java]: Agree. Corrected

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java (hunk 8 above)
Comment (jmdelfa) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java]: The original fix for the RecurrenceGoal required to access the activity duration (there were no way to access it). The final solution used an alternative method, but it seemed to me useful to allow access to the duration for future needs. If the policy in Aerie is to remove any code that is not used, then it should be removed.

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/Goal.java (hunk 1 above)
Comment (jmdelfa) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/Goal.java:236]: There are many examples in the code where == null was used (few right above this one). Any particular reason why you consider to use requireNonNull particularly in this case?

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java (hunk 8 above)
Comment (Mythicaeda) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java]: Thanks for the explanation! Since it is unused, please remove it.

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java (hunk 9 above)
Comment (jmdelfa) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/goals/RecurrenceGoal.java:215]: This if condition add conflicts whenever there is a valid time window to place an activity. As an example, if the goal window is larger than the planning horizon (e.g. [0,21] vs [0,20]), the last potential interval where activities could be placed should be discarded, as it is beyond the planning horizon. In the past the scheduler was wrongly allocating activities beyond the plan horizon as this check wasn't done.

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java (hunk 5 above)
Comment (skovati) [reply scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java]: Sounds good! Maybe we can update the comment with a brief explanation

**Comment by jmdelfa** [comment]
Updates already pushed.

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java (hunk 5 above)
Comment (jmdelfa) [reply scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/TestApplyWhen.java]: In this example I have removed the comment: //cutting of mid interval ... The outcome of the test was already properly defined at the beginning of the method. This test is also more clear as there is more room to place the goal. Regarding TestRecurrenceBabyWindow, I have added my answer to the beginning of the method.

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java (hunk 8 above)
Comment (jmdelfa) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java]: Done!

Comment (Mythicaeda) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java]: I still see this method. Was the change removing it pushed?

Comment (jmdelfa) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityExpression.java]: I haven't pushed it yet. I wanted to make sure that you are ok with the answer to your next question

**Review by skovati — APPROVED** [review]
Looks good to me! Thanks for the additional scheduler test and managing all the back and forth on this PR. 🚀
