### PR TITLE
Fix infinite loop issue with recurrence goal and global scheduling condition + warning message

### LINKED ISSUE #458: Scheduler warnings on timing precision
The scheduler generates many warnings of the form:

```
aerie_scheduler | [scheduler-agent] WARN gov.nasa.jpl.aerie.scheduler.constraints.activities.ActivityCreationTemplate - 
Root-finding is likely to fail as activity has an uncontrollable duration and the timing precision is 0. 
Setting it for you at 1s. 
Next time, use withTimingPrecision() when building the template.
```

But there is no way to specify a timing precision within the scheduling goal DSL, neither on the `CoexistenceGoal` itself nor on the `ActivityTemplate` as indicated.

Here is an example goal that causes the problem:

```ts
export default (): Goal => {
  return Goal.CoexistenceGoal({
    forEach: Real.Resource(Resources['/geometry/altitude_jupiter_km']).lessThan(165000),
    activityTemplate: ActivityTemplates.BGSet({
      primaryBody: 'PLUS_Y_NADIR_DECK',
      primaryTarget: 'PLANET',
      primarySpeedOfLightCorrection: 'NEGATIVE',
      secondaryBody: 'PLUS_X_ARRAY_AXIS',
      secondaryTarget: 'APPROACH_UNIQUE_X',
      secondarySpeedOfLightCorrection: 'ZERO',
    }),
    startsAt: TimingConstraint.singleton(WindowProperty.START),
  });
};
```

Internal ticket: https://jira.jpl.nasa.gov/browse/AERIEQS-341

### LINKED ISSUE #524: Scheduling with a recurrence goal and global condition causes infinite loop in worker
@duranb and I discovered this when he was working on https://github.com/NASA-AMMOS/aerie-ui/pull/293. You can use the branch from https://github.com/NASA-AMMOS/aerie-ui/pull/293 to make a global condition in the UI, otherwise replace step (6) below with an API call.

Repro steps:

1. Start with a fresh local deployment of develop (starting from no images, containers, or volumes)
2. Open UI: http://localhost/models
3. Upload a Banananation model JAR built from latest develop
4. Create a plan from `2022-318T00:00:00` to `2022-319T00:00:00`
5. Goto http://localhost/scheduling/goals/new?modelId=1&&specId=1 and create a recurrence goal:

    ```ts
    export default (): Goal =>
      Goal.ActivityRecurrenceGoal({
        activityTemplate: ActivityTemplates.BakeBananaBread({ temperature: 325.0, tbSugar: 2, glutenFree: false }),
        interval: Temporal.Duration.from({ hours: 2 }),
      });
    ```

6. Goto http://localhost/scheduling/conditions/new?modelId=1&&specId=1 and create a condition:

    ```ts
    export default function myFirstSchedulingCondition(): GlobalSchedulingCondition {
      return GlobalSchedulingCondition.scheduleActivitiesOnlyWhen(Real.Resource('/fruit').lessThan(3.0));
    }
    ```

7. Open the plan you created from (4) and add a `BiteBanana` activity to the plan at `2022-318T11:00:00`. Update the `biteSize` parameter to `10` (or anything that causes /fruit to be less than 3)
8. Simulate to verify the /fruit resource drops below 3
9. Open the scheduling panel and run scheduling 

This causes an infinite loop in the worker that picks up the scheduling run. Here are the logs from the worker:

```
[PG-JDBC I/O (1)] INFO gov.nasa.jpl.aerie.scheduler.worker.ListenSchedulerCapability - Received PSQL Notification: 94, scheduling_request_notification, {"specification_revision":1,"specification_id":1,"analysis_id":1}
[main] INFO gov.nasa.jpl.aerie.scheduler.server.remotes.postgres.PostgresResultsCellRepository - Claimed scheduling request with specification id SpecificationId[id=1]
(node:40) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[main] WARN gov.nasa.jpl.aerie.scheduler.constraints.activities.ActivityCreationTemplate - Root-finding is likely to fail as activity has an uncontrollable duration and the timing precision is 0. Setting it for you at 1s. Next time, use withTimingPrecision() when building the template.
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BiteBanana,SchedulingActivityInstanceId[id=0],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=2],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=4],+12:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=6],+14:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=8],+16:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=10],+18:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=12],+20:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=14],+22:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=16],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=18],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=20],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=22],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=24],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=26],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=28],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=30],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=32],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=34],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=36],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=38],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=40],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=42],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=44],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=46],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=48],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=50],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=52],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=54],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=56],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=58],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=60],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=62],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=64],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=66],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=68],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=70],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=72],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=74],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=76],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=78],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=80],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=82],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=84],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=86],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=88],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=90],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=92],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=94],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=96],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=98],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=100],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=102],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=104],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=106],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=108],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=110],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=112],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=114],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=116],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=118],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=120],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=122],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=124],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=126],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=128],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=130],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=132],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=134],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=136],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=138],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=140],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=142],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=144],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=146],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=148],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=150],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=152],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=154],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=156],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=158],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=160],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=162],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=164],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=166],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=168],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=170],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=172],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=174],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=176],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=178],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=180],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=182],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=184],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=186],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=188],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=190],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=192],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=194],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=196],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=198],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=200],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=202],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=204],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=206],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=208],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=210],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=212],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=214],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=216],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=218],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=220],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=222],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=224],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=226],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=228],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=230],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=232],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=234],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=236],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=238],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=240],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=242],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=244],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=246],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=248],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=250],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=252],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=254],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=256],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=258],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=260],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=262],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=264],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=266],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=268],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=270],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=272],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=274],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=276],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=278],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=280],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=282],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=284],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=286],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=288],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=290],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=292],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=294],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=296],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=298],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=300],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=302],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=304],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=306],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=308],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=310],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=312],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=314],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=316],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=318],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=320],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=322],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=324],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=326],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=328],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=330],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=332],+11:00:00.000000,{}]
[main] WARN gov.nasa.jpl.aerie.scheduler.simulation.SimulationFacade - Activity has unconstrained duration [BakeBananaBread,SchedulingActivityInstanceId[id=334],+11:00:00.000000,{}]
```

Essentially this causes `SchedulingActivityInstanceId[id=X]` to be printed out forever where `X` is always increasing.

### PR DESCRIPTION
**Pull request by adrienmaillard**
Resolves #524 
Resolves #458 

* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

The interval for specifying when to schedule activities was specified as Closed/Closed when it should have been Closed/Open to avoid multiple schedulings at the same time (at the end of the interval). 

## Verification

The bug reported in #524 was reproduced and has been added as test. Instead of looping forever, the scheduler only adds one activity as expected. 

## Documentation

N/A

## Future work

None

### CODE REVIEW

**Review by mattdailis — APPROVED** [review]

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java [hunk 1]
```diff
@@ -160,8 +160,9 @@ protected ActivityCreationTemplate fill(final ActivityCreationTemplate template)
                                      + " because its DurationType is Uncontrollable");
         }
         if(this.acceptableAbsoluteTimingError.isZero()){
-          logger.warn("Root-finding is likely to fail as activity has an uncontrollable duration and the timing "
-          + "precision is 0. Setting it for you at 1s. Next time, use withTimingPrecision() when building the template.");
+          //TODO: uncomment when precision can be set by user
+          //logger.warn("Root-finding is likely to fail as activity has an uncontrollable duration and the timing "
+          //+ "precision is 0. Setting it for you at 1s. Next time, use withTimingPrecision() when building the template.");
           this.acceptableAbsoluteTimingError = Duration.of(500, Duration.MILLISECOND);
```
Comment (Mythicaeda) [inline scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java:166]: Quick question based on the logger text that was commented out: Is the acceptableAbsoluteTimingError meant to be half of the timing precision? Because the text says it's setting the precision to 1s, but `acceptableAbsoluteTimingError` is set to .5s.

**Review by Mythicaeda — APPROVED** [review]

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java (hunk 1 above)
Comment (adrienmaillard) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java:166]: We want to represent the acceptable error around the desired value x, such that the result falls into [x-error, x+error]. The total error will be 0.5 * 2. We can change the sentence if you come up with something better.

Comment (Mythicaeda) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/constraints/activities/ActivityCreationTemplate.java:166]: This can wait until we're adding back the logger warning, but based on your explanation it sounds like the precision is actually 0.5s (as the acceptable range is +-0.5s)
