### PR TITLE
Return the Executing Directive Id in Simulation Error Response

### LINKED ISSUE #659: Include more information with simulation error messages
When a simulation fails, it would be really helpful to include the sim time at which the error occurred in the error message that displays in the error console, as well as the name and ID of the activity that threw the error. This would make it _much_ easier to track down issues in the simulation.

```[tasklist]
### Tasks
- [x] Display simulation time at which the error occurred
- [x] Display id of activity that threw the error, if the error was thrown by an activity
```

### PR DESCRIPTION
**Pull request by Mythicaeda**
* **Tickets addressed:** Closes #659 
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

If an activity directive throws an exception while executing, the offending directive id will now be included in the `data` part of the `reason` under the `executingDirectiveId` key.

This was accomplished by wrapping exceptions raised while stepping tasks in a `SpanException`. When this exception is caught, the driver will attempt to get the `directiveId` from that span before rewrapping the exception into a `SimulationException`, providing this id if it was found. Additionally, when a SimulationException is returned as the `reason` for a SimFailure, the `message` field is now populated with the exceptions message;

## Verification

The `SimulationExceptionResponse` tests were added.

In order to support these tests, the foo mission model gained a simulation configuration parameter and a new activity type. 
- The `raiseException` parameter will trigger a daemon task that throws a runtime exception 1hr in a plan if enabled
- The `DaemonCheckerSpawner` will call a `DaemonCheckerActivity` after `spawnDelay` minutes have passed, allowing us to throw runtime exceptions on demand/see the interaction between child activities and daemon tasks.

## Documentation

No docs need to be updated.

## Future work

- Posting the failed sim results to the DB
- Returning more information about the executing directive (ie name, the lineage from the source directive if it was a child that threw)
- If a daemon task throws an exception, is there anything we can return?

### CODE REVIEW

File: merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationDriver.java [hunk 1]
```diff
@@ -161,8 +177,11 @@ void simulateTask(final MissionModel<Model> missionModel, final TaskFactory<Retu
       engine.scheduleTask(Duration.ZERO, missionModel.getDaemon());
       {
         final var batch = engine.extractNextJobs(Duration.MAX_VALUE);
-        final var commit = engine.performJobs(batch.jobs(), cells, elapsedTime, Duration.MAX_VALUE);
-        timeline.add(commit);
+          final var commit = engine.performJobs(batch.jobs(), cells, elapsedTime, Duration.MAX_VALUE);
+          timeline.add(commit.getLeft());
+          if(commit.getRight().isPresent()) {
+             throw new Error("Exception thrown while starting daemon tasks", commit.getRight().get());
```
Comment (mattdailis) [inline merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationDriver.java]: I think `Error` is a little strong here - perhaps `RuntimeException`? Generally, we use `Error` to indicate a bug in our own code, kind of a "this shouldn't happen". If it can be triggered by user actions, let's use a subclass of Exception instead of Error, which is a Throwable but not an Exception.

Comment (Mythicaeda) [reply merlin-driver/src/main/java/gov/nasa/jpl/aerie/merlin/driver/SimulationDriver.java]: I've changed them to `RuntimeException`s 👍

**Review by mattdailis — APPROVED** [review]
🎉
