### PR TITLE
Make rootfinding robust to functions with discontinuities 

### LINKED ISSUE #1139: Scheduler rootfinding fails with ZeroDerivativeException
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

develop

### Describe the bug

Rootfinding is failing when one of the 2 init values (x1 and x2) leads to simulation exception. It needs to be more robust to this case. Maybe iterate in the domain until you have 2 valid values ? 

### Reproduction

With the 1.12 eurc model. 
Planning horizon : 2030-001 to 2030-002.
First goal: 
```
export default (): Goal => {
  return Goal.ActivityRecurrenceGoal({
    interval: Temporal.Duration.from({hours: 3}),
    activityTemplate:ActivityTemplates.ECM_Power_ON()
  })
}
```
Second goal: 
```
export default () => Goal.CoexistenceGoal({
  forEach: ActivityExpression.ofType(ActivityTypes.ECM_Power_ON),
  activityTemplate: ActivityTemplates.ECM_Power_OFF(),
  endsWithin: TimingConstraint.range(WindowProperty.END, Operator.PLUS, Temporal.Duration.from({ minutes: 15})),
})
```

The first goal is satisfied. 
The second goal misses the first two `ECM_Power_OFF` activities because rootfinding is failing. 
It is failing for the first `ECM_Power_OFF` activity because one of the bound is 2030-001T00:00:00. When a power off is simulated at this time, simulation fails (probably because it is a the same time that the power on?). Thus, one of the 2 init value of rootfinding is +inf. Which leads in the end to a derivative equal to 0.  

### Logs

_No response_

### System Info

```shell
develop, clipper eurc model
```

### Severity

Moderate

### PR DESCRIPTION
**Pull request by adrienmaillard**
* **Tickets addressed:** Fixes #1139 
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

- To specifically handle discontinuities (=simulation exceptions here): when a discontinuity is detected when computing f(x), another x is chosen randomly in the interval of possible x. 
- The optimization discussed in #1046 is applied, that is, assume that the duration function is secretly constant.
- A refactor to separate solving f(x) = y and f(x) = 0 (and the simple coordinate change between the two) to make rootfinding more apparent, clearer 

## Verification

Two tests on discontinuous functions and one test on f(x) = x^2 

## Documentation

None

## Future work

None

### CODE REVIEW

File: merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/types/Duration.java [hunk 1]
```diff
@@ -439,6 +439,16 @@ public boolean noShorterThan(final Duration other) {
     return this.compareTo(other) >= 0;
   }
 
+  /**
+   * Determine whether this duration lies in [lower bound, upper bound], bounds comprised
+   * @param lowerBound the lower bound, inclusive
+   * @param upperBound the upper bound, inclusive
+   * @return true if lies in the interval, false otherwise
+   */
+  public boolean liesIn(final Duration lowerBound, final Duration upperBound){
```
Comment (Mythicaeda) [inline merlin-sdk/src/main/java/gov/nasa/jpl/aerie/merlin/protocol/types/Duration.java]: Minor, can ignore:
```suggestion
  public boolean between(final Duration lowerBound, final Duration upperBound){
```

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/EquationSolvingAlgorithms.java [hunk 2]
```diff
@@ -64,79 +82,204 @@ public static class NoSolutionException extends Exception{
...
+    }
+
+    /**
+     * Solves x s.t. f(x) = 0
+     */
+    public RootFindingResult<Duration, Metadata> findRoot(
+        final Function<Duration, Metadata> f,
+        final History<Duration, Metadata> history,
+        final Duration x0,
+        final Duration x1,
```
Comment (adrienmaillard) [inline scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/EquationSolvingAlgorithms.java]: remove x1, we don't need it anymore

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/UncontrollableDurationTest.java [hunk 3]
```diff
@@ -219,11 +220,10 @@ public void testScheduleExceptionThrowingTask(){
...
-    assertTrue(TestUtility.containsActivity(plan,
-                                            planningHorizon.fromStart("PT120S"),
-                                            planningHorizon.fromStart("PT120S"),
-                                            problem.getActivityType("LateRiser")));
-    assertEquals(3, problem.getSimulationFacade().countSimulationRestarts());
+    assertTrue(TestUtility.atLeastOneActivityOfTypeInRange(plan,
+                                                           Interval.between(Duration.of(1, Duration.MINUTES), Duration.of(2,Duration.MINUTES)),
+                                                           problem.getActivityType("LateRiser")
+                                                           ));
   }
```
Comment (adrienmaillard) [inline scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/UncontrollableDurationTest.java]: Update comment and put exact interval boundaries

Comment (adrienmaillard) [reply scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/UncontrollableDurationTest.java]: ANd do not lose sim restart counting

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/EquationSolvingAlgorithms.java [hunk 4]
```diff
@@ -64,79 +82,204 @@ public static class NoSolutionException extends Exception{
...
+     * @param function the function we are trying to call
+     * @param init the initial x value
+     * @param min the lower bound of the domain of x
+     * @param max the upper bound of the domain of x
+     * @param history the querying history of f
+     * @param maxIteration the maximum number of iteration possible
+     * @return a coordinate (x, f(x)) s.t. f is continuous at x.
+     * @throws ExceededMaxIterationException
+     */
+    private IteratingResult tryValueAtUntilExhaustion(
```
Comment (Mythicaeda) [inline scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/EquationSolvingAlgorithms.java]: Minor, can ignore: I'm still trying to think if there's a more concise name that could be used. Would `valueAround` (or maybe `getValueAround`/`findValueAround`) fit? The `Around` communicates that the method doesn't necessarily return the function's output at `init`.

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/RootfindingTest.java [hunk 5]
```diff
@@ -0,0 +1,167 @@
...
+    if(power == 0){
+      return Duration.of(1, Duration.MICROSECONDS);
+    }
+    final var lv = duration.in(Duration.MICROSECONDS);
+    var res = lv;
+    for(int i = 1; i < power; i++){
+      res = res * lv;
+    }
+    return Duration.of(res, Duration.MICROSECONDS);
+  }
```
Comment (Mythicaeda) [inline scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/RootfindingTest.java]: Minor, can ignore: this method can be simplified into a one liner at its callsite:

```java
final var ret = Duration.of((long) Math.pow(x.in(Duration.MICROSECONDS), 2), Duration.MICROSECONDS);
```

**Review by Mythicaeda — COMMENTED** [review]
Looks good so far! Awaiting the changes we discussed yesterday.

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/RootfindingTest.java [hunk 6]
```diff
@@ -0,0 +1,167 @@
...
+  final Duration zeroSecond = Duration.of(0, Duration.SECONDS);
+  final static Duration oneSecond = Duration.of(1, Duration.SECONDS);
+  final Duration twoSecond = Duration.of(2, Duration.SECONDS);
+  final Duration threeSecond = Duration.of(3, Duration.SECONDS);
+  final Duration thirtySecond = Duration.of(30, Duration.SECONDS);
+
+  //compared with the testSimpleDiscontinuous, the function is discontinuous for all odd x, rootfinding is hitting
+  //discontinuous values multiple times
+  @Test
+  void testHighlyDiscontinuous()
```
Comment (Mythicaeda) [inline scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/RootfindingTest.java:19]: Question: The tests cover `f(x)=2x, x is not odd`, which is a removable discontinuity, but how does the algorithm handle the jump discontinuities or vertical asymptotes? Especially asymptotes, as I can imagine it wouldn't notice jump discontinuities unless the jump wasn't defined on either side (ie `f(x) = floor(x), x != 1` would have no value at 1).

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/EquationSolvingAlgorithms.java (hunk 4 above)
Comment (adrienmaillard) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/EquationSolvingAlgorithms.java]: Not sure about that. I wanted to call it `infaillibleValueAt` but it can still fail if too many iterations...

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/RootfindingTest.java (hunk 5 above)
Comment (adrienmaillard) [reply scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/RootfindingTest.java]: haha indeed.

File: scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/EquationSolvingAlgorithms.java (hunk 4 above)
Comment (adrienmaillard) [reply scheduler-driver/src/main/java/gov/nasa/jpl/aerie/scheduler/EquationSolvingAlgorithms.java]: `nextValueAt` it is

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/RootfindingTest.java (hunk 6 above)
Comment (adrienmaillard) [reply scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/RootfindingTest.java:19]: added the test

File: scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/UncontrollableDurationTest.java [hunk 7]
```diff
@@ -219,10 +220,10 @@ public void testScheduleExceptionThrowingTask(){
     final var plan = solver.getNextSolution().get();
     //Activity can be started in [0, 2m] but this activity will throw an exception if ran in [0, 1m] so it is scheduled at 2m (as being the second bounds the rootfinding tries before search).
     assertTrue(TestUtility.containsActivity(plan,
-                                            planningHorizon.fromStart("PT120S"),
-                                            planningHorizon.fromStart("PT120S"),
+                                            planningHorizon.fromStart("PT1M38.886061S"),
+                                            planningHorizon.fromStart("PT1M38.886061S"),
                                             problem.getActivityType("LateRiser")));
-    assertEquals(3, problem.getSimulationFacade().countSimulationRestarts());
+    assertEquals(4, problem.getSimulationFacade().countSimulationRestarts());
```
Comment (Mythicaeda) [inline scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/UncontrollableDurationTest.java:226]: Why is there an additional restart now?

Comment (adrienmaillard) [reply scheduler-driver/src/test/java/gov/nasa/jpl/aerie/scheduler/UncontrollableDurationTest.java:226]: because before, the second bound (x1) was tested immediately after x0 and was outside of the non-working interval. The randomness needs one more iteraration to find such a point.

**Review by Mythicaeda — APPROVED** [review]
