### PR TITLE
Serialize `NoSuchMissionModel` exception out in activity validations

### LINKED ISSUE #1329: Automatic Activity Validation Doesn't Handle Plans without Mission Models
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

2.2.2, develop

### Describe the bug

Migrated an Aerie venue from a version pre-automatic validations to v2.2.2 and Aerie Merlin began freaking out failing to validate activities of presumably plans without mission models. This presumption comes from the error message saying it can't find model 0, but model 0 literally cannot exist in the DB (mission model ids start at 1). My assumption is that it somehow translated a `null` model id to `0`.

So this bug is twofold:
1: Fix the parse to persist the `null` 
2: Gracefully handle `null` model ids (ie warning but marking as complete or setting the validation error to something like "no mission model")

### Reproduction

I imagine this can be replicated on an already-migrated version by creating a plan, adding activities, deleting the model, and updating the arguments of an activity (done via the API, as the UI doesn't like plans w/o models).

### Logs

```shell
2024-02-14 10:49:23	
[Thread-0] ERROR gov.nasa.jpl.aerie.merlin.server.services.ValidationWorker - Validation request failed due to no such mission model: gov.nasa.jpl.aerie.merlin.server.services.MissionModelService$NoSuchMissionModelException: No mission model exists with id `0`
	
2024-02-14 10:49:22	
[Thread-0] ERROR gov.nasa.jpl.aerie.merlin.server.services.ValidationWorker - Validation request failed due to no such mission model: gov.nasa.jpl.aerie.merlin.server.services.MissionModelService$NoSuchMissionModelException: No mission model exists with id `0`
	
2024-02-14 10:49:21	
[Thread-0] ERROR gov.nasa.jpl.aerie.merlin.server.services.ValidationWorker - Validation request failed due to no such mission model: gov.nasa.jpl.aerie.merlin.server.services.MissionModelService$NoSuchMissionModelException: No mission model exists with id `0`
	
2024-02-14 10:49:21	
[Thread-0] ERROR gov.nasa.jpl.aerie.merlin.server.services.ValidationWorker - Validation request failed due to no such mission model: gov.nasa.jpl.aerie.merlin.server.services.MissionModelService$NoSuchMissionModelException: No mission model exists with id `0`
	
2024-02-14 10:49:19	
[Thread-0] ERROR gov.nasa.jpl.aerie.merlin.server.services.ValidationWorker - Validation request failed due to no such mission model: gov.nasa.jpl.aerie.merlin.server.services.MissionModelService$NoSuchMissionModelException: No mission model exists with id `0`
```

### System Info

```shell
M1 Mac
```

### Severity

Minor

### PR DESCRIPTION
**Pull request by skovati**
* **Tickets addressed:** closes #1329 
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description
Adds a `try` `catch (NoSuchMissionModelException` deeper within the validation worker loop, so we can catch these exceptions within each model batch iteration, generate a `NoSuchMissionModelError` for each validation requested for that model batch, and write them out to the database.

This avoids the issue of the worker loop only catching this exception at its outer iteration layer, which would simply print an error and then restart the main validation loop without resolving the `pending` validation, so it would run into the same issue over and over.

## Verification

Added a new test `AutomaticValidationTests::noSuchMissionModel`. Running this test without the second commit of this PR will fail and output
```
Expected :NoSuchMissionModelFailure[message=no such mission model, modelId=0]
Actual   :Pending[]
```

After applying the second commit, the test will pass.

## Documentation

None

## Future work

None

### CODE REVIEW

File: e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/AutomaticValidationTests.java [hunk 1]
```diff
@@ -130,6 +132,30 @@ void instantiationError() throws IOException, InterruptedException {
     ), activityValidation);
   }
 
+  @Test
+  void noSuchMissionModelError() throws IOException, InterruptedException {
```
Comment (skovati) [inline e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/AutomaticValidationTests.java:135]: The new test added

File: e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/types/ActivityValidation.java [hunk 2]
```diff
@@ -11,6 +11,7 @@ record Success() implements ActivityValidation {}
   record InstantiationFailure(List<String> extraneousArguments, List<String> missingArguments, List<?> unconstructableArguments) implements ActivityValidation {}
   record ValidationFailure(List<ValidationNotice> notices) implements ActivityValidation {}
   record NoSuchActivityTypeFailure(String message, String activityType) implements ActivityValidation {}
+  record NoSuchMissionModelFailure(String message, String modelId) implements ActivityValidation {}
```
Comment (skovati) [inline e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/types/ActivityValidation.java:14]: A new validation failure type that captures the mission model load failure

File: e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/types/ActivityValidation.java [hunk 3]
```diff
@@ -44,6 +45,10 @@ static ActivityValidation fromJSON(JsonObject obj) {
                         getStringArray($, "subjects"),
                         $.asJsonObject().getString("message"))));
       case "NO_SUCH_ACTIVITY_TYPE" -> new NoSuchActivityTypeFailure(errors.getJsonObject("noSuchActivityError").getString("message"), errors.getJsonObject("noSuchActivityError").getString("activity_type"));
+      case "NO_SUCH_MISSION_MODEL" -> new NoSuchMissionModelFailure(
```
Comment (skovati) [inline e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/types/ActivityValidation.java:48]: deserialize JSON to `NoSuchMissionModelFailure`

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java [hunk 4]
```diff
@@ -191,6 +191,14 @@ public static JsonValue serializeBulkArgumentValidationResponse(BulkArgumentVali
       return Json.createObjectBuilder(serializeInstantiationException(f.ex()).asJsonObject())
           .add("type", "INSTANTIATION_ERRORS")
           .build();
+    } else if (response instanceof BulkArgumentValidationResponse.NoSuchMissionModelError m) {
```
Comment (skovati) [inline merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java:194]: Serializer for new validation failure type

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java [hunk 5]
```diff
@@ -136,7 +136,16 @@ public List<BulkArgumentValidationResponse> validateActivityArgumentsBulk(
       final List<ActivityDirectiveForValidation> activities
   ) throws NoSuchMissionModelException, MissionModelLoadException {
     // load mission model once for all activities
-    final var modelType = this.loadMissionModelType(modelId.toString());
+    ModelType<?, ?> modelType;
+    try {
+      modelType = this.loadMissionModelType(modelId.toString());
+      // try and catch NoSuchMissionModel here, so we can serialize it out to each activity validation
+      // rather than catching it at a higher level in the workerLoop itself
+    } catch (NoSuchMissionModelException e) {
```
Comment (skovati) [inline merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java:143]: The new deeper `catch` that can handle and map this exception to actual failed validations (which resolves them from `pending`, instead of just printing the error and restarting the loop.

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ValidationWorker.java [hunk 6]
```diff
@@ -49,9 +49,6 @@ public void workerLoop() {
           final var duration = (endTime - beginTime) / 1_000_000.0;
           logger.debug("processed model batch of size {} in {} ms", unvalidatedDirectives.size(), duration);
         }
-
-      } catch (NoSuchMissionModelException ex) {
```
Comment (skovati) [inline merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ValidationWorker.java:53]: Removed the outer `catch`, since we handle this for each model batch now.

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java [hunk 7]
```diff
@@ -191,6 +191,14 @@ public static JsonValue serializeBulkArgumentValidationResponse(BulkArgumentVali
...
+      return Json.createObjectBuilder()
+                 .add("errors", Json.createObjectBuilder()
+                     .add("noSuchMissionModelError", serializeNoSuchMissionModelException(m.ex()))
+                     .build())
+                 .add("success", JsonValue.FALSE)
+                 .add("type", "NO_SUCH_MISSION_MODEL")
+                 .build();
```
Comment (Mythicaeda) [inline merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java]: Extremely minor, nonblocking: could you reorder this so the keys are added in the same order as in the other responses (ie `Validation`, `NoSuchActivityError`)?

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java [hunk 8]
```diff
@@ -136,7 +136,16 @@ public List<BulkArgumentValidationResponse> validateActivityArgumentsBulk(
       final List<ActivityDirectiveForValidation> activities
   ) throws NoSuchMissionModelException, MissionModelLoadException {
```
Comment (Mythicaeda) [inline merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java]: `NoSuchMissionModelException` isn't getting thrown by this method anymore and can be removed from the signature.

**Review by Mythicaeda — APPROVED** [review]
Two nonblocking issues, but otherwise LGTM!

**Review by Mythicaeda — APPROVED** [review]

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java (hunk 8 above)
Comment (skovati) [reply merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/LocalMissionModelService.java]: Change has been made in the latest commit

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java (hunk 7 above)
Comment (skovati) [reply merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java]: Change has been made!
