### PR TITLE
Permissions for sequence templates

### LINKED ISSUE #1686: sequencing server fails to check permissons for template features
### Checked for duplicates

No - I haven't checked

### Is this a regression?

No - This is a new bug

### Version

develop

### Describe the bug

The routes for expanding templates and applying sequence filters in the sequencing server aren't present in the permissions checking logic, so running in `user` mode doesn't work. (Using `aerie_admin` short-circuits the checks.)

https://github.com/NASA-AMMOS/aerie/blob/e2c840912a78267332731ee8cd18c4b3fc1b9cb5/sequencing-server/src/utils/hasura.ts#L22-L47

### Reproduction

Try to apply a sequence filter or expand sequence templates in `user` mode.

### Logs

```shell

```

### System Info

```shell
develop, local
```

### Severity

Moderate

### PR DESCRIPTION
**Pull request by cartermak**
Closes #1686 

## Description

Creates permissions for expanding templates and applying sequence filters and specifies those permissions for the corresponding routes.

See matching aerie-ui PR: NASA-AMMOS/aerie-ui#1700

## Verification

Updated automated tests using my best pattern recognition skills. Also tested manually by applying sequence filters and expanding templates in a local deployment with the `user` role selected. Ran migrations and checked contents in pgAdmin were as expected.

## Documentation

https://github.com/NASA-AMMOS/aerie-docs/pull/234

### CODE REVIEW

File: deployment/hasura/migrations/Aerie/22_template_permissions/down.sql [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+    'expand_all_activities',
+    'insert_ext_dataset',
+    'resource_samples',
+    'schedule',
+    'sequence_seq_json_bulk',
+    'simulate'
+  );
+
+update permissions.user_role_permission
+set action_permissions = action_permissions - 'expand_all_templates' - 'assign_activities_by_filter';
```
Comment (Mythicaeda) [inline deployment/hasura/migrations/Aerie/22_template_permissions/down.sql]: Update needs to happen first

Comment (cartermak) [reply deployment/hasura/migrations/Aerie/22_template_permissions/down.sql]: Done, ty

File: deployment/hasura/migrations/Aerie/22_template_permissions/up.sql [hunk 2]
```diff
@@ -0,0 +1,24 @@
+drop type permissions.action_permission_key;
+
+create type permissions.action_permission_key
+  as enum (
+    'check_constraints',
+    'create_expansion_rule',
+    'create_expansion_set',
+    'expand_all_activities',
+    'expand_all_templates',
+    'assign_activities_by_filter',
```
Comment (Mythicaeda) [inline deployment/hasura/migrations/Aerie/22_template_permissions/up.sql]: Please put this in alphabetical order. This also applies to the original location in `permissions.sql`, as well as when in `default_user_roles.sql`

Comment (cartermak) [reply deployment/hasura/migrations/Aerie/22_template_permissions/up.sql]: done

**Review by Mythicaeda — APPROVED** [review]

**Comment by dandelany** [comment]
Thanks all, merging with https://github.com/NASA-AMMOS/aerie-ui/pull/1700
