### PR TITLE
[Aerie-1117]  Return compilation errors with constraints

### LINKED ISSUE #1117: Return Compilation Errors When Constraints Fail to Compile
When running Constraints, if a constraint has errors that prevent it from compiling, the Merlin Server does not include these errors in its response. This means that the only way to see what the error was is to open the container's Docker log and look for the exception. These errors should instead be parsed and returned as part of the response payload.

### PR DESCRIPTION
**Pull request by goetzrrGit**
* **Tickets addressed:** Closes #1117
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description
Currently, if a constraint compilation error occurs, the server swallows it, making it difficult for users to develop constraints in Aerie. This is because users cannot see why the constraint is not running or where the error is located.

This PR changes this behavior by capturing compilation errors and sending them back to the UI, which will display them in the UI console. This will allow users to quickly identify and fix compilation errors, improving their constraint development experience.

Additionally, this PR updates the Hasura action to support sending back errors or results per constraint. This will be used in a future PR to stop the Merlin server from short-circuiting and not running the full list of constraints.

We will also need to merge in the UI PR which allows the frontend to support this modified Hasura call
https://github.com/NASA-AMMOS/aerie-ui/pull/967

## Verification
Updated e2e test 

## Documentation
None

## Future work
https://github.com/NASA-AMMOS/aerie/issues/1194

### CODE REVIEW

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java
Comment (Mythicaeda) [inline merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java:1]: Constraints can also fail with an `InputMismatchException`, either during part of the setup before compilation or during evaluation of the constraints. Since this exception is part of constraints, it would make sense for it to also have it's serlializer updated like the success and compilation failure cases

File: e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/ConstraintsTests.java
Comment (Mythicaeda) [inline e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/ConstraintsTests.java:1]: In this file, can you add some assertions about the `success` and `errors` fields on the tests where you replaced a `.get` with a `.get.result`?

File: e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/types/CachedConstraintRun.java [hunk 1]
```diff
@@ -18,7 +18,7 @@ public static CachedConstraintRun fromJSON(JsonObject json) {
         json.getBoolean("definition_outdated"),
         json.getJsonObject("results").isEmpty() ?
             Optional.empty() :
-            Optional.of(ConstraintRecord.fromJSON(json.getJsonObject("results")))
+            Optional.of(ConstraintResult.fromJSON(json.getJsonObject("results")))
```
Comment (Mythicaeda) [inline e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/types/CachedConstraintRun.java:21]: Just to confirm: the reason why the Cached Results no longer equal what is returned from the endpoint is because we only want to cache successful constraint runs (as in, there were no errors during execution)? If so, will #1194 cause any complications?

Comment (goetzrrGit) [reply e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/types/CachedConstraintRun.java:21]: Since we weren't storing failed runs in the first place, I don't see this causing any issues. The original behavior would impose constraints that only compiled correctly, preventing compilation errors from being stored in the cache or database. We only care about runs that compiled and executed successfully on the server. With #1194, we'll filter out any errors and only store successful runs to the database and cache..

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java
Comment (goetzrrGit) [reply merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/http/ResponseSerializers.java:1]: Yep, that is correct. I am going to handle all the setup/parsing errors with https://github.com/NASA-AMMOS/aerie/issues/1194 right now I was only focused on sending back a `compilation error` as that seems to be the most helpful.

File: e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/ConstraintsTests.java
Comment (goetzrrGit) [reply e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/ConstraintsTests.java:1]: Sure, I just updated the test to include that check.

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintAction.java [hunk 2]
```diff
@@ -165,9 +166,9 @@ public List<ConstraintResult> getViolations(final PlanId planId, final Optional<
         if (constraintCompilationResult instanceof ConstraintsDSLCompilationService.ConstraintsDSLCompilationResult.Success success) {
           expression = success.constraintExpression();
         } else if (constraintCompilationResult instanceof ConstraintsDSLCompilationService.ConstraintsDSLCompilationResult.Error error) {
-          throw new ConstraintCompilationException("Constraint compilation failed: " + error);
+          throw new ConstraintCompilationException(entry.getValue().name(),error);
         } else {
-          throw new ConstraintCompilationException("Unhandled variant of ConstraintsDSLCompilationResult: " + constraintCompilationResult);
+          throw new Error("Unhandled variant of ConstraintsDSLCompilationResult: " + constraintCompilationResult);
```
Comment (Mythicaeda) [inline merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintAction.java]: I think this makes sense as a ConstraintCompilationException, as it's an error that is explicitly called when Constraints Compilation returned an abnormal state.

File: e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/ConstraintsTests.java [hunk 3]
```diff
@@ -438,13 +455,13 @@ void compilationFailsOutdatedSimulationSimDatasetId() throws IOException {
       // This test causes the endpoint to throw an exception when it fails to compile the constraint,
       // as it cannot find the external dataset resource in the set of known resource types.
       // "input mismatch exception" is the return msg for this error
```
Comment (Mythicaeda) [inline e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/ConstraintsTests.java]: Minor: The "input mismatch exception" part of the comment needs to be updated

File: merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintAction.java (hunk 2 above)
Comment (goetzrrGit) [reply merlin-server/src/main/java/gov/nasa/jpl/aerie/merlin/server/services/ConstraintAction.java]: Made the required change.

File: e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/ConstraintsTests.java (hunk 3 above)
Comment (goetzrrGit) [reply e2e-tests/src/test/java/gov/nasa/jpl/aerie/e2e/ConstraintsTests.java]: oops, That is what I get for not reading the comment fully. I removed that line.

**Review by Mythicaeda — APPROVED** [review]
LGTM! Marking as `Don't Merge` until [the UI PR](https://github.com/NASA-AMMOS/aerie-ui/pull/967) is also ready to merge.
