### PR TITLE
Fix enum types for scheduling eDSL presets

### LINKED ISSUE #916: Cannot use ActivityPresets with Enum Values in Scheduling EDSL
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

develop

### Describe the bug

Goals that use ActivityPresets to define the `activityTemplate` or `activityFinder` fields fail to compile with a type error if the ActivityType of the preset has an enum parameter.

Example Error:
```json
[{"errors":
  [{"location":
    {"column":52,"line":5},
    "message":"TypeError: TS2345 Argument of type '{ peelDirection: string; }' is not assignable to parameter of type 'ParameterTypePeelBanana'.\n  Types of property 'peelDirection' are incompatible.\n    Type 'string' is not assignable to type '\"fromStem\" | \"fromTip\" | Discrete<\"fromStem\" | \"fromTip\">'.","stack":"at (5:52)"}],"goal_id":3}]
```

This may potentially also occur with `activityFinder`.

### Reproduction

1. Spin up Aerie.
2. Upload a BananaNation model and create a plan from it.
3. Create a preset for PeelBanana.
4. Create the following scheduling goal for the plan:
```typescript
export default (): Goal => {
  return Goal.CoexistenceGoal({
    forEach: Real.Resource("/peel").greaterThan(3),
    activityFinder: ActivityExpression.build(ActivityTypes.PeelBanana, ActivityPresets.PeelBanana["FromTip"]),
    activityTemplate: ActivityTemplates.PeelBanana(ActivityPresets.PeelBanana["FromTip"]),
    startsAt: TimingConstraint.singleton(WindowProperty.START).plus(Temporal.Duration.from({ minutes: 5 }))
  });
}
```
5. Attempt to run simulation. 

### Logs

_No response_

### System Info

```shell
Firefox
M1 Mac
```

### Severity

Moderate

### PR DESCRIPTION
**Pull request by JoelCourtney**
* **Tickets addressed:** Closes #916 
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

This fixes a bug where presets that included enum parameters caused the eDSL compiler to give a type error.

This is because the type was not specific enough: the preset's type was inferred to be `string`, which is not specific enough to be applied to a type like `"option1" | "option2"`, even if the actual value of the the preset was `"option1"`. The presets now have the proper type annotation.

Also, in a previous PR I changed the function `valueSchemaToTypescriptType` to `valueSchemaToTypescriptTypeOrProfile` for no apparent reason. I've reverted that change here.

## Verification

I added a unit test to SchedulingDSLCompilationServiceTests.

### CODE REVIEW

File: scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingDSLCompilationServiceTests.java [hunk 1]
```diff
@@ -41,6 +41,7 @@
 import java.util.Optional;
 
 import static gov.nasa.jpl.aerie.merlin.protocol.types.Duration.HOUR;
+import static gov.nasa.jpl.aerie.merlin.protocol.types.Duration.MICROSECOND;
```
Comment (skovati) [inline scheduler-worker/src/test/java/gov/nasa/jpl/aerie/scheduler/worker/services/SchedulingDSLCompilationServiceTests.java]: Very minor: unused import

File: scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/TypescriptCodeGenerationService.java [hunk 2]
```diff
@@ -183,16 +189,20 @@ static String toString(final TypescriptType type) {
...
       } else if (type instanceof TSArray t) {
-        final var typeStr = toString(t.elementType());
+        final var typeStr = toString(t.elementType(), true);
         return "((" +typeStr+ ")[] | Discrete<("+typeStr+")[]>)";
       } else if (type instanceof TSStruct t) {
 
         var typeStr = "{ ";
         for(final var keyAndType :  t.keysAndTypes()){
-          typeStr += keyAndType.getLeft() + ":"+ toString(keyAndType.getRight())+",";
+          typeStr += keyAndType.getLeft() + ":"+ toString(keyAndType.getRight(), true)+",";
```
Comment (skovati) [inline scheduler-server/src/main/java/gov/nasa/jpl/aerie/scheduler/server/services/TypescriptCodeGenerationService.java]: If `keysAndTypes` is relatively large, it might be more performant to make `typeStr` a `StringBuilder` and append within the loop.

**Review by skovati — APPROVED** [review]
Looks really good to me!

**Comment by skovati** [comment]
Re-triggered the e2e tests since they failed due to that flaky timeout 👍
