### PR TITLE
Fix directive source invocation id in merge and snapshots

### LINKED ISSUE #1690: Migration 19 bug in tables related to activity_directive
Noted by @Mythicaeda on slack, Migration 19 was merged recently but has an issue that we should fix, notably **before** merging https://github.com/NASA-AMMOS/aerie-ui/pull/1663 since it uses related tables/functions

## Description
* Migration 19 added a column `source_scheduling_goal_invocation_id` to the `merlin.activity_directive` table
* `merlin` has three other tables which are meant to "mirror" the structure of `activity_directive`: `activity_directive_changelog`, `plan_snapshot_activities` and `merge_staging_area` but weren't updated to add the new column
* Per @Mythicaeda this means the contents of the column will be lost when:
    - restoring from a snapshot
    - undoing a change to an activity
    - the activity is added into a parent plan by a merge request

## Proposed fix
* After discussion, I think the most practical thing is to add a new patch migration (20) to add the new fields, rather than retroactively fixing migration 19, **unless** we determine that there could be data loss by migrating directly from 18 -> 19 -> 20.
* We should add a comment or something to `activity_directive` to note the mirror tables to try to prevent this in future
* @Mythicaeda is there any additional code change necessary here or just adding the new column?

### Reproduction

Migrate up from 18 to 19        

### Version

develop

### Severity

Major

### PR DESCRIPTION
**Pull request by JoelCourtney**
* **Tickets addressed:** closes #1690 
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description
When I added the `source_scheduling_goal_invocation_id` field to `activity_directive`, there were a bunch of places I forgot to update relating to plan merging, duplicating, and snapshots. This makes an extra migration that does these things. Thanks @Mythicaeda

### CODE REVIEW

File: deployment/postgres-init-db/sql/functions/merlin/snapshots/restore_from_snapshot.sql [hunk 1]
```diff
@@ -54,10 +54,12 @@ create procedure merlin.restore_from_snapshot(_plan_id integer, _snapshot_id int
 
 		-- Upsert the rest
 		insert into merlin.activity_directive (
-		      id, plan_id, name, source_scheduling_goal_id, created_at, created_by, last_modified_at, last_modified_by,
+		      id, plan_id, name, source_scheduling_goal_id, source_scheduling_goal_invocation_id,
+		      created_at, created_by, last_modified_at, last_modified_by,
 		      start_offset, type, arguments, last_modified_arguments_at, metadata,
 		      anchor_id, anchored_to_start)
-		select psa.id, _plan_id, psa.name, psa.source_scheduling_goal_id, psa.created_at, psa.created_by, psa.last_modified_at, psa.last_modified_by,
+		select psa.id, _plan_id, psa.name, psa.source_scheduling_goal_id, psa.source_scheduling_goal_invocation_id,
```
Comment (Mythicaeda) [inline deployment/postgres-init-db/sql/functions/merlin/snapshots/restore_from_snapshot.sql:61]: The invocation id also needs to be set during the update part of the upsert (L71):

```sql
source_scheduling_goal_id = excluded.source_scheduling_goal_id,
source_scheduling_goal_invocation_id = excluded.source_scheduling_goal_invocation_id,
created_at = excluded.created_at,
```

File: deployment/postgres-init-db/sql/functions/merlin/merging/commit_merge.sql [hunk 2]
```diff
@@ -47,7 +49,8 @@ begin
         and ca.change_type_supplying = 'delete'
     union
     select  _request_id, activity_id, name, tags.tag_ids_activity_snapshot(ca.activity_id, psa.snapshot_id),
-            source_scheduling_goal_id, created_at, created_by, last_modified_by, start_offset, type, arguments, metadata, anchor_id, anchored_to_start,
+            source_scheduling_goal_id, created_at, source_scheduling_goal_invocation_id,
```
Comment (Mythicaeda) [inline deployment/postgres-init-db/sql/functions/merlin/merging/commit_merge.sql]: These columns are reversed on this line:
```suggestion
            source_scheduling_goal_id, source_scheduling_goal_invocation_id, created_at,
```

File: deployment/postgres-init-db/sql/tables/merlin/activity_directive/activity_directive_changelog.sql
Comment (Mythicaeda) [inline deployment/postgres-init-db/sql/tables/merlin/activity_directive/activity_directive_changelog.sql:1]: `hasura.restore_activity_changelog` in `hasura_functions.sql` needs to be uploaded to load from the new column on this table.

**Review by Mythicaeda — COMMENTED** [review]
There are three small locations that still need to be touched up

**Comment by JoelCourtney** [comment]
Looks like your review comments ended up fixing the e2e tests too. 👍  @Mythicaeda

File: deployment/hasura/migrations/Aerie/20_patch_activity_goal_invocation_id/up.sql [hunk 3]
```diff
@@ -0,0 +1,824 @@
...
+$$;
+
+alter table merlin.plan_snapshot_activities
+  add column source_scheduling_goal_invocation_id integer;
+
+alter table merlin.merge_staging_area
+  add column source_scheduling_goal_invocation_id integer;
+
+comment on column merlin.merge_staging_area.source_scheduling_goal_id is e''
+  'The invocation of the scheduling goal that generated this activity directive to be committed.';
```
Comment (Mythicaeda) [inline deployment/hasura/migrations/Aerie/20_patch_activity_goal_invocation_id/up.sql]: Typo in the column name:
```suggestion
comment on column merlin.merge_staging_area.source_scheduling_goal_invocation_id is e''
  'The invocation of the scheduling goal that generated this activity directive to be committed.';
```

Comment (Mythicaeda) [reply deployment/hasura/migrations/Aerie/20_patch_activity_goal_invocation_id/up.sql]: ...But I see that that was caused by the same typo in `merge_staging_area` (L55)

**Review by Mythicaeda — APPROVED** [review]
Thanks for tackling this!
