### PR TITLE
Bug fix for coexistence goal valueAt usage

### LINKED ISSUE #1378: CoexistenceGoal based on Resource with negative startsAt condition throws NoSuchElementException when scheduling
### Checked for duplicates

No - I haven't checked

### Is this a regression?

No - This is a new bug

### Version

2.5.0

### Describe the bug

The bug occurs when a `CoexistenceGoal` with a `forEach` focused on a resource window, where the `activityTemplate` uses `valueAt`s has a `startsAt` with a negative offset. A clearer example follows:
```typescript
export default (): Goal => {
  var prePostPadding: Temporal.Duration = Temporal.Duration.from({ minutes: 5 });
  return Goal.CoexistenceGoal({ 
    forEach: Discrete.Resource("maneuvers_type").notEqual("NONE"), 
    activityTemplate: interval => {
      // start time
      var sp: Spans = Spans.FromInterval(interval)
      return ActivityTemplates.ManPrePost({
        estimatedDuration: Discrete.Resource("maneuvers_duration").valueAt(sp.starts()), 
        maneuverType: Discrete.Resource("maneuvers_type").valueAt(sp.starts()),
        additionalNotes: Discrete.Resource("maneuvers_additionalNotes").valueAt(sp.starts()), 
        startTime: Discrete.Resource("maneuvers_startTime").valueAt(sp.starts()),
        prePostPadding: prePostPadding 
      })
    },
    startsAt: TimingConstraint.singleton(WindowProperty.START).minus(prePostPadding)
  })
}
```
This goal works fine if the `.minus` in the `startsAt` is not present, or if it is but the forEach depends on an activity, like so:
```typescript
export default (): Goal => {
  var prePostPadding: Temporal.Duration = Temporal.Duration.from({ minutes: 5 });

  return Goal.CoexistenceGoal({ 
    forEach: ActivityExpression.ofType(ActivityType.ManExec), 
    activityTemplate: activity => {
      return ActivityTemplates.ManPrePost({
        estimatedDuration: activity.parameters.estimatedDuration,
        maneuverType: activity.parameters.maneuverType,
        additionalNotes: activity.parameters.additionalNotes,
        startTime: activity.parameters.startTime,
        prePostPadding: prePostPadding 
      })
    },
    startsAt: TimingConstraint.singleton(WindowProperty.START).minus(prePostPadding)
  })
}
```

### Reproduction

To reproduce this issue:
- create a model that has a precomputed resource, such as an enum. We will refer to that as `resourceName`, of enum type `resourceEnum`.
- create an activity that has an exported parameter with that type. We will refer to this activity as `ActivityName` with parameter `resourceEnumParam`.
- create a scheduling goal that places instances of `ActivityName` using the following logic:
```typescript
export default (): Goal => {
  return Goal.CoexistenceGoal({ 
    forEach: Discrete.Resource("resourceName").equal("VALUE"), 
    activityTemplate: interval => {
      var sp: Spans = Spans.FromInterval(interval)
      return ActivityTemplates.ActivityName({
        resourceEnumParam: Discrete.Resource("resourceName").valueAt(sp.starts())
      })
    },
    startsAt: TimingConstraint.singleton(WindowProperty.START).minus(Temporal.Duration.from({ minutes: 5 }))
  })
}
```

### Logs

```shell
The stack trace:
java.util.NoSuchElementException
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at gov.nasa.jpl.aerie.constraints.tree.ValueAt.evaluate(ValueAt.java:31)
	at gov.nasa.jpl.aerie.constraints.tree.ValueAt.evaluate(ValueAt.java:17)
	at gov.nasa.jpl.aerie.constraints.tree.ProfileExpression.evaluate(ProfileExpression.java:20)
	at gov.nasa.jpl.aerie.scheduler.model.SchedulingActivityDirective.lambda$instantiateArguments$1(SchedulingActivityDirective.java:272)
	at java.base/java.util.HashMap.forEach(Unknown Source)
	at gov.nasa.jpl.aerie.scheduler.model.SchedulingActivityDirective.instantiateArguments(SchedulingActivityDirective.java:270)
	at gov.nasa.jpl.aerie.scheduler.constraints.activities.ActivityExpression.matches(ActivityExpression.java:342)
	at gov.nasa.jpl.aerie.scheduler.constraints.activities.ActivityExpression.matches(ActivityExpression.java:297)
	at gov.nasa.jpl.aerie.scheduler.model.PlanInMemory.find(PlanInMemory.java:177)
	at gov.nasa.jpl.aerie.scheduler.goals.CoexistenceGoal.getConflicts(CoexistenceGoal.java:243)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.getConflicts(PrioritySolver.java:709)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.satisfyGoalGeneral(PrioritySolver.java:591)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.satisfyGoal(PrioritySolver.java:434)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.solve(PrioritySolver.java:390)
	at gov.nasa.jpl.aerie.scheduler.solver.PrioritySolver.getNextSolution(PrioritySolver.java:177)
	at gov.nasa.jpl.aerie.scheduler.worker.services.SynchronousSchedulerAgent.schedule(SynchronousSchedulerAgent.java:224)
	at gov.nasa.jpl.aerie.scheduler.worker.SchedulerWorkerAppDriver.main(SchedulerWorkerAppDriver.java:100)
```

### System Info

```shell
Firefox Version 115.9.0esr (64-bit)
MacOS Ventura (13.6.5)
```

### Severity

Minor

### PR DESCRIPTION
**Pull request by adrienmaillard**
* **Tickets addressed:** Closes #1378 
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

The interval for instantiating parameters of an activity has been relaxed to `Interval.FOREVER` instead of restricting it to the start time of the activity.

## Verification

A new test reproducing the failure has been added and is now passing.

## Documentation

None. 

## Future work

I found #1484 while working on this one.

### CODE REVIEW

File: constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ListExpressionAt.java [hunk 1]
```diff
@@ -22,9 +22,6 @@ public DiscreteProfile evaluate(final SimulationResults results, final Interval
     //Even if the expression returns a discrete profile, this profile has a constant value, a list of serialized values,
     //at the singleton timepoint it has been computed at.
     //The instantiation and use of valueAt is necessary here because the profile are not only discrete but also "continuous" in the form of linear profiles.
-    if(!bounds.isSingleton()){
-      throw new Error("The ListExpressionAt node should be used only with singleton bounds.");
-    }
```
Comment (Mythicaeda) [inline constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ListExpressionAt.java]: Why has  the `isSingleton` check been removed from here and `StructExpressionAt`?

Comment (Mythicaeda) [reply constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ListExpressionAt.java]: Never mind, it's because of the relaxation 🤦‍♀️. 

Couple of follow-ups:
1) The comments directly above the removals are now out of date, as they refer to this singleton enforcement.
2) Follow up question: is `Interval.FOREVER` the only non-singleton value permitted?

Comment (adrienmaillard) [reply constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ListExpressionAt.java]: 2. No it is not the only possible value at this level. It's only in the instantiate method in `SchedulingActivityDirective` that it does not make sense to restrict the evaluation interval.

File: constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ListExpressionAt.java [hunk 2]
```diff
@@ -22,9 +22,6 @@ public DiscreteProfile evaluate(final SimulationResults results, final Interval
...
     final var retList = new ArrayList<SerializedValue>();
     for (final var field: elements) {
       retList.add(field.evaluate(results, bounds, environment)
```
Comment (JoelCourtney) [inline constraints/src/main/java/gov/nasa/jpl/aerie/constraints/tree/ListExpressionAt.java]: My concern here is that it is still being evaluated at `bounds.start`, and you've changed the bounds to `Interval.FOREVER`. Previously I used the bounds to tell these nodes when to evaluated the profiles, but now I think we need a separate argument so we don't evaluate everything at `Duration.MIN`.

**Review by JoelCourtney — CHANGES_REQUESTED** [review]

**Comment by adrienmaillard** [comment]
@JoelCourtney and I discussed this and we found another way of fixing the issue.

**Comment by adrienmaillard** [comment]
I haven't added a nested parameter test. It's not straightforward at all and I'd prefer investigate this in another ticket.

**Review by JoelCourtney — APPROVED** [review]
