### PR TITLE
Trigger function in scheduling_specification correctly updates spec revision

### LINKED ISSUE #1191: Scheduling specification revision is not updated when a goal is updated
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

develop

### Describe the bug

The `increment_revision_on_goal_update` trigger on `scheduling_specification` should update the revision of the specification every time a goal in that spec is updated but the increment_revision_on_goal_update() has an error:
Line 
` where g.specification_id = new.id`
should be 
`where g.goal_id = new.id`
as the new is referring to a scheduling_goal row and not a specification

@Mythicaeda and I have discovered this issue while working on #1170.

### Reproduction

Will do a DB test in a PR.

### Logs

_No response_

### System Info

```shell
Develop, macOS, local deployment
```

### Severity

Minor

### PR DESCRIPTION
**Pull request by adrienmaillard**
* **Tickets addressed:** Fixes #1191 
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

Fix the function called by trigger

## Verification

Added a db-test 

## Documentation

None

## Future work

None

### CODE REVIEW

File: db-tests/src/test/java/gov/nasa/jpl/aerie/database/SchedulerDatabaseTests.java [hunk 1]
```diff
@@ -133,6 +133,27 @@ void shouldErrorWhenInsertingNonConsecutivePriority() throws SQLException {
...
+          select revision from scheduling_specification
+          where id = %d;
+          """.formatted(specificationId));
+      res.next();
+      return res.getInt("revision");
+    }
+
+    @Test
+    void shouldIncrementSpecRevisionAfterModifyingGoal() throws SQLException {
+      insertGoalPriorities(0, new int[] {0, 1, 2, 3, 4}, new int[]{0, 1, 2, 3, 4});
```
Comment (Mythicaeda) [inline db-tests/src/test/java/gov/nasa/jpl/aerie/database/SchedulerDatabaseTests.java:147]: Minor: clarity
```suggestion
      insertGoalPriorities(0, goalIds, new int[]{0, 1, 2, 3, 4});
```

Comment (Mythicaeda) [reply db-tests/src/test/java/gov/nasa/jpl/aerie/database/SchedulerDatabaseTests.java:147]: Misread how `insertGoalPriorities` worked, ignore this comment.

**Review by Mythicaeda — APPROVED** [review]
